name: Worklog CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Run TEST pipeline
        run: |
          /home/simeon/deploy_worklog.sh

  deploy-prod:
    needs: test
    runs-on: self-hosted
    environment:
      name: production

    steps:
      - name: Deploy to PROD
        run: |
          /home/simeon/deploy_worklog_prod.sh