name: Deploy Worklog

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy latest main to live folder
        shell: bash
        run: |
          set -euxo pipefail
          cd /home/simeon/worklog
          git fetch origin main
          git reset --hard origin/main

      - name: Restart worklog service
        shell: bash
        run: |
          sudo -n /usr/bin/systemctl restart worklog.service
          sudo -n /usr/bin/systemctl status worklog.service --no-pager

          # deploy test